### ISSUE TITLE
it would be awesome if it would work for tvOS!

### ISSUE THREAD

**Issue by GINNOV** [rob-nash/Rotary#1]
that would deserve a bitcoin beer ;-)

**Comment by rob-nash** [comment]
beer! woop!

I'll take a look this afternoon, see what I can do. if it's too hard, I'll let you know and continue with playstation 4.

**Comment by rob-nash** [comment]
All [done](https://github.com/rob-nash/Rotary/releases/tag/1.1.1).
Demo [here](https://github.com/rob-nash/DancerWheel).

I smell beer!

**Comment by rob-nash** [comment]
When is the beer bitcoin arriving bro ?

**Comment by rob-nash** [comment]
@kywix for as long as this issue is open, passers by will identify you as dishonest. That works for me.
